### ISSUE TITLE
testing: commport path mismatch

### ISSUE THREAD

**Issue by junkvolny** [themighty1/lpfw#10]
Testing fails (doesn't even start), because inside file:
https://github.com/themighty1/lpfw/blob/master/testmain.cpp#L156
you use path:
ifstream portfile("/tmp/commport");

But inside file:
https://github.com/themighty1/lpfw/blob/master/lpfw.cpp#L882
you use different path:
ofstream myfile("/tmp/lpfwcommport");

By the way, why don't you use header file with constants for such string constants with paths ?! This is what you get for copy-pasting... Your code has 1000x repeating same constants over and over, that's just stinky coding.

**Comment by themighty1** [comment]
I agree that the testing code leaves much to be desired, mainly because it was a work in progress and not meant for user consumption.
Feel free to get in touch with me on IRC if you need any questions to be answered quickly.
I'm dansmith_btc on freenode.net IRC, I'm available in the channel tlsnotary-chat

**Comment by junkvolny** [comment]
after discussion in IRC, new branch "develop" published, I tested, it's fixed there
